CREATE TABLE IF NOT EXISTS producto (
    id SERIAL PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    tipo_vehiculo VARCHAR(50) NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    precio_costo NUMERIC(12,2) NOT NULL,
    precio_venta NUMERIC(12,2) NOT NULL,
    stock INT NOT NULL DEFAULT 0
);
ALTER TABLE producto ADD COLUMN IF NOT EXISTS marca VARCHAR(100);
ALTER TABLE producto ADD COLUMN IF NOT EXISTS modelo VARCHAR(100);
ALTER TABLE producto ADD COLUMN IF NOT EXISTS anio INTEGER;
ALTER TABLE producto ADD COLUMN IF NOT EXISTS proveedor VARCHAR(100);
ALTER TABLE producto ADD COLUMN IF NOT EXISTS descripcion TEXT;
SELECT * FROM producto;