spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.zeozdkgetncpjmhircxg
spring.datasource.password=motorespuesto
spring.datasource.driver-class-name=org.postgresql.Driver
